### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sfomina** [JackieW001/turbo-dollop#2]
- Include why this is significant and what questions it will provoke
- Explain how urbanization will be on the x-axis 
- Why is population included on the graph/relevant?

**Comment by DimitriyL** [comment]
1. It is significant because it will attempt to describe the relationship that exists between urbanization, income, and population and prevalence of the fast food industry. Given the obesity epidemic that exists in low-income, urban communities, in part due to the influence of "empty calorie" consumption that fast food entails, I would say that it is extremely relevant to modern life.
2. We could include it as a toggle option, such as by giving the user the ability to switch between urbanization, population, and income. We could also use a roundabout route, such as by representing it via the size of each dot.
3. Because it allows us a way of viewing how densely packed the restaurants are (i.e. how many residents to a restaurant).
